import { configEnv } from "./config/EnvExtracter";
import { connect } from "./config/database/connection";
import express from "express";
import { UsersRouter } from "./routes/usersRoute";
import { errorHandler } from "./error/errorHandler";
import { CardsRouter } from "./routes/cardsRoute";
import morgan from "morgan";
var cors = require("cors");
const app = express();
app.set("trust proxy", true);
app.use(morgan("tiny"));
configEnv();
app.use(cors({ origin: process.env.CLIENT_URL }));
connect();

app.use(express.json());
app.listen(8081);
app.use("/users", UsersRouter);
app.use("/cards", CardsRouter);
app.use(errorHandler);
